# Generated by Django 5.0.14 on 2026-08-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(blank=True, max_length=255)),
                ('mpn_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('naspo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_file', models.CharField(max_length=80)),
                ('duplicate_vendor_mpn', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='naspo.vendor')),
            ],
        ),
    ]
